include:
  - ./external-api/docker-compose.external-api.yml

services:
  web1:
    extends:
      file: docker-compose.common.yml
      service: web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:8.0.30-debian
    # Poderia usar um envfile para mais dinamismo
    # restart: on-failure=5
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s # interval - com que frequência o healthcheck é executado
      timeout: 5s # timeout - tempo máximo para o healthcheck responder
      retries: 5 # retries - número de tentativas antes de considerar o serviço como unhealthy
      start_period: 10s # start_period - tempo de espera antes de iniciar as verificações de saúde
      # Ou seja, o healthcheck será executado a cada 30 segundos, com um timeout de 5 segundos, 5 tentativas e um tempo de espera inicial de 10 segundos.
    # networks:
    #   - external-api_default
    
  
# networks:
#   external-api_default:
#     external: true

# Para host.docker.internal funcionar no Linux e no mac
#mac ou lnux (/etc/hosts)

# Windows (C:\Windows\System32\drivers\etc\hosts)

# 127.0.0.1 host.docker.internal
